name: translator_without_state_management
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  line_icons: ^2.0.3
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
